services:
  backend:
    image: kientrandinhhoang/mern-backend:1.0
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
    extra_hosts:
      - "ac-w6rdtks-shard-00-00.qjhchyl.mongodb.net:159.143.84.253"
      - "ac-w6rdtks-shard-00-01.qjhchyl.mongodb.net:159.143.85.14"
      - "ac-w6rdtks-shard-00-02.qjhchyl.mongodb.net:159.143.85.24"

  frontend:
    image: kientrandinhhoang/mern-frontend:1.0
    ports:
      - "5173:80"
    depends_on:
      - backend
